services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -u root -prootpass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_HOST: db       # keep this (Docker service name)
      DB_PORT: 3306     # container port
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: studentdb
    ports:
      - "8080:8080"

volumes:
  dbdata:
