version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: studentdb-mysql
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    ports: ["3306:3306"]
    volumes: [ "dbdata:/var/lib/mysql" ]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: student-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: studentdb
    ports: ["8080:8080"]
    restart: unless-stopped

volumes:
  dbdata:
